language: php
php:
- 5.5
#-5.4
#- hhvm

addons:
  code_climate:
    repo_token: 6fdcc9f41ae8f03876ddb127a094a262809518a20b798bdfbc06dbb117c831bb

after_script:
  - vendor/bin/test-reporter

before_script:
  - composer update --prefer-source

script:
  - phpunit --colors --coverage-text
  - php coverage-checker.php clover.xml 75

notifications:
  email:
    on_failure: change
