language: php
php:
- 5.5
#-5.4
#- hhvm

before_script:
  - composer update --prefer-source

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - php coverage-checker.php clover.xml 75

after_script: php vendor/bin/coveralls


notifications:
  email:
    on_failure: change
