language: php

sudo: false

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    secure: Yc+Xohkr/iEUU7FCQuSLXAE9ywNW9g6CfrM1Ki0Hl+fS15F3AXT7dFY8EyCJ4dP1/oI0dBmwrGWrltXV0XWIjGV1Ms3tefCgQpBBAqwT+hImzVP3RbpZW8Iyo2d0VgiDemQF1LWYD/pKu6d8WljTnv5D77NIMdEJjQ0uzeTLWdw=

install:
  - composer install --prefer-dist

before_script:
  - git config --global user.email "travis-ci@codeclimate.com"
  - git config --global user.name "Travis CI"

script:
  - vendor/bin/phpunit

after_script:
  - php composer/bin/test-reporter


notifications:
  email:
    on_failure: change
