language: php
php:
- 5.5
#-5.4
#- hhvm

before_script:
  - composer update --prefer-source

script:
  - phpunit
  - php coverage-checker.php clover.xml 75
  
notifications:
  irc:
    channels:
      - "chat.freenode.net#durhamTeam7"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
