<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        require __DIR__ . '/swansonAlgorithm/algorithm.php';
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
